namespace OrderProcessing.Api.Models;

/// <summary>
/// Tracks stock for a single product. AvailableQuantity is stock that can still be reserved;
/// ReservedQuantity is stock already held against in-flight orders (Task 3's Inventory service
/// moves quantity between the two, guarding against overselling under concurrent requests).
/// </summary>
public class InventoryItem
{
    /// <summary>Business key — no separate surrogate id, since callers always address inventory
    /// by ProductId per the assessment's endpoints (GET/POST /api/inventory/{productId}/...).</summary>
    public string ProductId { get; set; } = string.Empty;

    public int AvailableQuantity { get; set; }

    public int ReservedQuantity { get; set; }

    /// <summary>EF Core concurrency token (auto-generated by the InMemory provider on every
    /// update). Guards against two concurrent reservation requests both reading stale
    /// AvailableQuantity and over-reserving — wired up in Task 3 alongside the reservation logic
    /// that relies on it.</summary>
    public byte[] RowVersion { get; set; } = Array.Empty<byte>();
}
